<h2>Contatos</h2>

<p>
	<a class="btn btn-primary" href="<?php echo $this->url('admin/default',
	array('controller' => 'contatos', 'action' => 'cadastrar'))?>">Cadastrar novo</a>
</p>

<div class="well">
	<table class="table">
		<tr>
			<td>ID</td>
			<td>Nome</td>
			<td>Telefone</td>
			<td>Email</td>
			<td>Opções</td>
		</tr>
		<?php
		if(count($contatos)):
		foreach ($contatos as $contato): 
		?>
		<tr>
			<td><?php echo $contato->getId()?></td>
			<td><?php echo $contato->getNome()?></td>
			<td><?php echo $contato->getTelefone()?></td>
			<td><?php echo $contato->getEmail()?></td>
			<td>
				<a href="/admin/contatos/alterar/<?php echo $contato->getId()?>"><i class="glyphicon glyphicon-pencil"></i></a>
				<a onclick="return confirm('Deseja realmente excluir esse contato?')" href="<?php echo $this->url('admin/default',
					array('controller' => 'contatos', 'action' => 'excluir', 'id' => $contato->getId()))?>"><i class="glyphicon glyphicon-remove"></i></a>
			</td>
		</tr>
		<?php  
		endforeach;
		endif;	
		?>

	</table>

</div>